server:
  port=8089
spring:
  application:
    name: digipos
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=DIGIPOSDB
    username: sa
    password: P@23932w0rd
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        ddl-auto: update

